#pragma once

#define ERROR_TS_KEY 1
#define ERROR_CODE_KEY 2
#define ERROR_MESSAGE_KEY 3

#define WEATHER_TS_KEY 4
#define WEATHER_RESPONSE_TS_KEY 5
#define WEATHER_ID_KEY 6
#define WEATHER_ICON_KEY 7
#define WEATHER_DESCRIPTION_KEY 8
#define WEATHER_TEMPERATURE_KEY 9
#define WEATHER_HUMIDITY_KEY 10
#define WEATHER_PRESSURE_KEY 11
#define WEATHER_WIND_SPEED_KEY 12
#define WEATHER_WIND_DIRECTION_KEY 13
#define WEATHER_WIND_GUST_KEY 14
#define WEATHER_CLOUDS_KEY 15
#define WEATHER_RAIN_KEY 16
#define WEATHER_SNOW_KEY 17
#define WEATHER_LOC_CITY_KEY 18
#define WEATHER_LOC_COUNTRY_KEY 19
#define WEATHER_LOC_LAT_KEY 20
#define WEATHER_LOC_LON_KEY 21
#define WEATHER_LOC_SUNRISE_TS_KEY 22
#define WEATHER_LOC_SUNSET_TS_KEY 23

#define OPTIONS_CHANGED_TS_KEY 24
